const bugArr = 
[
    {
        "name": "Agrias Butterfly",
        "image_url": "https://dodo.ac/np/images/6/60/Agrias_Butterfly_NH_Icon.png",
        "location": "Flying near flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 3000
    },
    {
        "name": "Ant",
        "image_url": "https://dodo.ac/np/images/5/5d/Ant_NH_Icon.png",
        "location": "On rotten Turnips/Candy/Lollipops",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 80
    },
    {
        "name": "Atlas Moth",
        "image_url": "https://dodo.ac/np/images/7/7f/Atlas_Moth_NH_Icon.png",
        "location": "On trees (any kind)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM  4 AM",
        "weather": "Any weather",
        "sell_nook": 3000
    },
    {
        "name": "Bagworm",
        "image_url": "https://dodo.ac/np/images/1/17/Bagworm_NH_Icon.png",
        "location": "Shaking trees (hardwood and cedar)",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 600
    },
    {
        "name": "Banded Dragonfly",
        "image_url": "https://dodo.ac/np/images/3/35/Banded_Dragonfly_NH_Icon.png",
        "location": "Flying near water",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 4500
    },
    {
        "name": "Bell Cricket",
        "image_url": "https://dodo.ac/np/images/4/4a/Bell_Cricket_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM  8 AM",
        "weather": "Any except rain",
        "sell_nook": 430
    },
    {
        "name": "Blue Weevil Beetle",
        "image_url": "https://dodo.ac/np/images/2/20/Blue_Weevil_Beetle_NH_Icon.png",
        "location": "On palm trees",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 800
    },
    {
        "name": "Brown Cicada",
        "image_url": "https://dodo.ac/np/images/4/44/Brown_Cicada_NH_Icon.png",
        "location": "On trees (hardwood and cedar)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM  5 PM",
        "weather": "Any weather",
        "sell_nook": 250
    },
    {
        "name": "Centipede",
        "image_url": "https://dodo.ac/np/images/d/d2/Centipede_NH_Icon.png",
        "location": "From hitting rocks",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM  11 PM",
        "weather": "Any weather",
        "sell_nook": 300
    },
    {
        "name": "Cicada Shell",
        "image_url": "https://dodo.ac/np/images/d/d1/Cicada_Shell_NH_Icon.png",
        "location": "On trees (hardwood and cedar)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 10
    },
    {
        "name": "Citrus Long-Horned Beetle",
        "image_url": "https://dodo.ac/np/images/9/9a/Citrus_Long-Horned_Beetle_NH_Icon.png",
        "location": "On tree stumps",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any except rain",
        "sell_nook": 350
    },
    {
        "name": "Common Bluebottle",
        "image_url": "https://dodo.ac/np/images/2/21/Common_Bluebottle_NH_Icon.png",
        "location": "Flying",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM  7 PM",
        "weather": "Any except rain",
        "sell_nook": 300
    },
    {
        "name": "Common Butterfly",
        "image_url": "https://dodo.ac/np/images/f/f8/Common_Butterfly_NH_Icon.png",
        "location": "Flying",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM  7 PM",
        "weather": "Any except rain",
        "sell_nook": 160
    },
    {
        "name": "Cricket",
        "image_url": "https://dodo.ac/np/images/8/8f/Cricket_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM  8 AM",
        "weather": "Any except rain",
        "sell_nook": 130
    },
    {
        "name": "Cyclommatus Stag",
        "image_url": "https://dodo.ac/np/images/a/a0/Cyclommatus_Stag_NH_Icon.png",
        "location": "On palm trees",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 8000
    },
    {
        "name": "Damselfly",
        "image_url": "https://dodo.ac/np/images/c/c8/Damselfly_NH_Icon.png",
        "location": "Flying near water",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "weather": "Any except rain",
        "sell_nook": 500
    },
    {
        "name": "Darner Dragonfly",
        "image_url": "https://dodo.ac/np/images/5/5c/Darner_Dragonfly_NH_Icon.png",
        "location": "Flying near water",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 230
    },
    {
        "name": "Diving Beetle",
        "image_url": "https://dodo.ac/np/images/7/78/Diving_Beetle_NH_Icon.png",
        "location": "On rivers and ponds",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  7 PM",
        "weather": "Any weather",
        "sell_nook": 800
    },
    {
        "name": "Drone Beetle",
        "image_url": "https://dodo.ac/np/images/4/48/Drone_Beetle_NH_Icon.png",
        "location": "On trees (any kind)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 200
    },
    {
        "name": "Dung Beetle",
        "image_url": "https://dodo.ac/np/images/c/c4/Dung_Beetle_NH_Icon.png",
        "location": "Pushing snowballs",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 3000
    },
    {
        "name": "Earth-Boring Dung Beetle",
        "image_url": "https://dodo.ac/np/images/5/53/Earth-Boring_Dung_Beetle_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 300
    },
    {
        "name": "Emperor Butterfly",
        "image_url": "https://dodo.ac/np/images/c/cf/Emperor_Butterfly_NH_Icon.png",
        "location": "Flying near flowers",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "5 PM  8 AM",
        "weather": "Any except rain",
        "sell_nook": 4000
    },
    {
        "name": "Evening Cicada",
        "image_url": "https://dodo.ac/np/images/b/ba/Evening_Cicada_NH_Icon.png",
        "location": "On trees (hardwood and cedar)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM  8 AM &amp; 4 PM  7 PM",
        "weather": "Any weather",
        "sell_nook": 550
    },
    {
        "name": "Firefly",
        "image_url": "https://dodo.ac/np/images/d/d6/Firefly_NH_Icon.png",
        "location": "Flying near water",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "7 PM  4 AM",
        "weather": "Any except rain",
        "sell_nook": 300
    },
    {
        "name": "Flea",
        "image_url": "https://dodo.ac/np/images/8/89/Flea_NH_Icon.png",
        "location": "On villagers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 70
    },
    {
        "name": "Fly",
        "image_url": "https://dodo.ac/np/images/1/15/Fly_NH_Icon.png",
        "location": "Flying near trash or rotten turnips",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 60
    },
    {
        "name": "Giant Cicada",
        "image_url": "https://dodo.ac/np/images/e/e3/Giant_Cicada_NH_Icon.png",
        "location": "On trees (hardwood and cedar)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM  5 PM",
        "weather": "Any weather",
        "sell_nook": 500
    },
    {
        "name": "Giant Stag",
        "image_url": "https://dodo.ac/np/images/0/08/Giant_Stag_NH_Icon.png",
        "location": "On trees (any kind)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "11 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 10000
    },
    {
        "name": "Giant Water Bug",
        "image_url": "https://dodo.ac/np/images/8/86/Giant_Water_Bug_NH_Icon.png",
        "location": "On rivers and ponds",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 2000
    },
    {
        "name": "Giraffe Stag",
        "image_url": "https://dodo.ac/np/images/c/c7/Giraffe_Stag_NH_Icon.png",
        "location": "On palm trees",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 12000
    },
    {
        "name": "Golden Stag",
        "image_url": "https://dodo.ac/np/images/b/ba/Golden_Stag_NH_Icon.png",
        "location": "On palm trees",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 12000
    },
    {
        "name": "Goliath Beetle",
        "image_url": "https://dodo.ac/np/images/3/3e/Goliath_Beetle_NH_Icon.png",
        "location": "On palm trees",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "5 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 8000
    },
    {
        "name": "Grasshopper",
        "image_url": "https://dodo.ac/np/images/3/37/Grasshopper_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 160
    },
    {
        "name": "Great Purple Emperor",
        "image_url": "https://dodo.ac/np/images/8/81/Great_Purple_Emperor_NH_Icon.png",
        "location": "Flying near flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM  7 PM",
        "weather": "Any except rain",
        "sell_nook": 3000
    },
    {
        "name": "Hermit Crab",
        "image_url": "https://dodo.ac/np/images/6/6b/Hermit_Crab_NH_Icon.png",
        "location": "Disguised on shoreline",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 1000
    },
    {
        "name": "Honeybee",
        "image_url": "https://dodo.ac/np/images/5/51/Honeybee_NH_Icon.png",
        "location": "Flying near flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 200
    },
    {
        "name": "Horned Atlas",
        "image_url": "https://dodo.ac/np/images/2/2a/Horned_Atlas_NH_Icon.png",
        "location": "On palm trees",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 8000
    },
    {
        "name": "Horned Dynastid",
        "image_url": "https://dodo.ac/np/images/1/10/Horned_Dynastid_NH_Icon.png",
        "location": "On trees (any kind)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 1350
    },
    {
        "name": "Horned Elephant",
        "image_url": "https://dodo.ac/np/images/e/ea/Horned_Elephant_NH_Icon.png",
        "location": "On palm trees",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 8000
    },
    {
        "name": "Horned Hercules",
        "image_url": "https://dodo.ac/np/images/2/21/Horned_Hercules_NH_Icon.png",
        "location": "On palm trees",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "5 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 12000
    },
    {
        "name": "Jewel Beetle",
        "image_url": "https://dodo.ac/np/images/4/43/Jewel_Beetle_NH_Icon.png",
        "location": "On tree stumps",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any except rain",
        "sell_nook": 2400
    },
    {
        "name": "Ladybug",
        "image_url": "https://dodo.ac/np/images/0/08/Ladybug_NH_Icon.png",
        "location": "On flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 200
    },
    {
        "name": "Long Locust",
        "image_url": "https://dodo.ac/np/images/9/9d/Long_Locust_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  7 PM",
        "weather": "Any weather",
        "sell_nook": 200
    },
    {
        "name": "Madagascan Sunset Moth",
        "image_url": "https://dodo.ac/np/images/6/69/Madagascan_Sunset_Moth_NH_Icon.png",
        "location": "Flying near flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  4 PM",
        "weather": "Any except rain",
        "sell_nook": 2500
    },
    {
        "name": "Man-Faced Stink Bug",
        "image_url": "https://dodo.ac/np/images/a/ac/Man-Faced_Stink_Bug_NH_Icon.png",
        "location": "On flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM  8 AM",
        "weather": "Any except rain",
        "sell_nook": 1000
    },
    {
        "name": "Mantis",
        "image_url": "https://dodo.ac/np/images/4/4e/Mantis_NH_Icon.png",
        "location": "On flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 430
    },
    {
        "name": "Migratory Locust",
        "image_url": "https://dodo.ac/np/images/d/d0/Migratory_Locust_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM  7 PM",
        "weather": "Any weather",
        "sell_nook": 600
    },
    {
        "name": "Miyama Stag",
        "image_url": "https://dodo.ac/np/images/0/0a/Miyama_Stag_NH_Icon.png",
        "location": "On trees (any kind)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 1000
    },
    {
        "name": "Mole Cricket",
        "image_url": "https://dodo.ac/np/images/4/4f/Mole_Cricket_NH_Icon.png",
        "location": "Underground",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 500
    },
    {
        "name": "Monarch Butterfly",
        "image_url": "https://dodo.ac/np/images/3/38/Monarch_Butterfly_NH_Icon.png",
        "location": "Flying near flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 140
    },
    {
        "name": "Mosquito",
        "image_url": "https://dodo.ac/np/images/8/84/Mosquito_NH_Icon.png",
        "location": "Flying",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "5 PM  4 AM",
        "weather": "Any except rain",
        "sell_nook": 130
    },
    {
        "name": "Moth",
        "image_url": "https://dodo.ac/np/images/a/a0/Moth_NH_Icon.png",
        "location": "Flying near light sources",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM  4 AM",
        "weather": "Any except rain",
        "sell_nook": 130
    },
    {
        "name": "Orchid Mantis",
        "image_url": "https://dodo.ac/np/images/a/a7/Orchid_Mantis_NH_Icon.png",
        "location": "On white flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 2400
    },
    {
        "name": "Paper Kite Butterfly",
        "image_url": "https://dodo.ac/np/images/9/9e/Paper_Kite_Butterfly_NH_Icon.png",
        "location": "Flying near flowers",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  7 PM",
        "weather": "Any except rain",
        "sell_nook": 1000
    },
    {
        "name": "Peacock Butterfly",
        "image_url": "https://dodo.ac/np/images/7/77/Peacock_Butterfly_NH_Icon.png",
        "location": "Flying near blue, purple, and black flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM  7 PM",
        "weather": "Any except rain",
        "sell_nook": 2500
    },
    {
        "name": "Pill Bug",
        "image_url": "https://dodo.ac/np/images/b/b9/Pill_Bug_NH_Icon.png",
        "location": "From hitting rocks",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "11 PM  4 PM",
        "weather": "Any weather",
        "sell_nook": 250
    },
    {
        "name": "Pondskater",
        "image_url": "https://dodo.ac/np/images/1/1f/Pondskater_NH_Icon.png",
        "location": "On rivers and ponds",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  7 PM",
        "weather": "Any weather",
        "sell_nook": 130
    },
    {
        "name": "Queen Alexandra's Birdwing",
        "image_url": "https://dodo.ac/np/images/b/bb/Queen_Alexandra%27s_Birdwing_NH_Icon.png",
        "location": "Flying near flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  4 PM",
        "weather": "Any except rain",
        "sell_nook": 4000
    },
    {
        "name": "Rainbow Stag",
        "image_url": "https://dodo.ac/np/images/f/f7/Rainbow_Stag_NH_Icon.png",
        "location": "On trees (any kind)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "7 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 6000
    },
    {
        "name": "Rajah Brooke's Birdwing",
        "image_url": "https://dodo.ac/np/images/8/81/Rajah_Brooke%27s_Birdwing_NH_Icon.png",
        "location": "Flying near flowers",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "8 AM  5 PM",
        "weather": "Any except rain",
        "sell_nook": 2500
    },
    {
        "name": "Red Dragonfly",
        "image_url": "https://dodo.ac/np/images/0/09/Red_Dragonfly_NH_Icon.png",
        "location": "Flying near water",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM  7 PM",
        "weather": "Any except rain",
        "sell_nook": 180
    },
    {
        "name": "Rice Grasshopper",
        "image_url": "https://dodo.ac/np/images/7/78/Rice_Grasshopper_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM  7 PM",
        "weather": "Any weather",
        "sell_nook": 400
    },
    {
        "name": "Robust Cicada",
        "image_url": "https://dodo.ac/np/images/a/a2/Robust_Cicada_NH_Icon.png",
        "location": "On trees (hardwood and cedar)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM  5 PM",
        "weather": "Any weather",
        "sell_nook": 300
    },
    {
        "name": "Rosalia Batesi Beetle",
        "image_url": "https://dodo.ac/np/images/7/7c/Rosalia_Batesi_Beetle_NH_Icon.png",
        "location": "On tree stumps",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any except rain",
        "sell_nook": 3000
    },
    {
        "name": "Saw Stag",
        "image_url": "https://dodo.ac/np/images/0/03/Saw_Stag_NH_Icon.png",
        "location": "On trees (any kind)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 2000
    },
    {
        "name": "Scarab Beetle",
        "image_url": "https://dodo.ac/np/images/e/ee/Scarab_Beetle_NH_Icon.png",
        "location": "On trees (any kind)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "11 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 10000
    },
    {
        "name": "Scorpion",
        "image_url": "https://dodo.ac/np/images/9/95/Scorpion_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM  4 AM",
        "weather": "Any weather",
        "sell_nook": 8000
    },
    {
        "name": "Snail",
        "image_url": "https://dodo.ac/np/images/e/e9/Snail_NH_Icon.png",
        "location": "On rocks and bushes",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Rain only",
        "sell_nook": 250
    },
    {
        "name": "Spider",
        "image_url": "https://dodo.ac/np/images/e/e0/Spider_NH_Icon.png",
        "location": "Shaking trees",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "7 PM  8 AM",
        "weather": "Any weather",
        "sell_nook": 600
    },
    {
        "name": "Stinkbug",
        "image_url": "https://dodo.ac/np/images/4/42/Stinkbug_NH_Icon.png",
        "location": "On flowers",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any except rain",
        "sell_nook": 120
    },
    {
        "name": "Tarantula",
        "image_url": "https://dodo.ac/np/images/b/b5/Tarantula_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "7 PM  4 AM",
        "weather": "Any weather",
        "sell_nook": 8000
    },
    {
        "name": "Tiger Beetle",
        "image_url": "https://dodo.ac/np/images/5/58/Tiger_Beetle_NH_Icon.png",
        "location": "On the ground",
        "n_m1": 0,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any except rain",
        "sell_nook": 1500
    },
    {
        "name": "Tiger Butterfly",
        "image_url": "https://dodo.ac/np/images/b/b6/Tiger_Butterfly_NH_Icon.png",
        "location": "Flying",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM  7 PM",
        "weather": "Any except rain",
        "sell_nook": 240
    },
    {
        "name": "Violin Beetle",
        "image_url": "https://dodo.ac/np/images/8/86/Violin_Beetle_NH_Icon.png",
        "location": "On tree stumps",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any except rain",
        "sell_nook": 450
    },
    {
        "name": "Walker Cicada",
        "image_url": "https://dodo.ac/np/images/f/f8/Walker_Cicada_NH_Icon.png",
        "location": "On trees (hardwood and cedar)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "8 AM  5 PM",
        "weather": "Any weather",
        "sell_nook": 400
    },
    {
        "name": "Walking Leaf",
        "image_url": "https://dodo.ac/np/images/b/b9/Walking_Leaf_NH_Icon.png",
        "location": "Disguised under trees",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 600
    },
    {
        "name": "Walking Stick",
        "image_url": "https://dodo.ac/np/images/5/58/Walking_Stick_NH_Icon.png",
        "location": "On trees (any kind)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM  8 AM &amp; 5 PM  7 PM",
        "weather": "Any weather",
        "sell_nook": 600
    },
    {
        "name": "Wasp",
        "image_url": "https://dodo.ac/np/images/a/a5/Wasp_NH_Icon.png",
        "location": "Shaking trees",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 2500
    },
    {
        "name": "Wharf Roach",
        "image_url": "https://dodo.ac/np/images/1/1f/Wharf_Roach_NH_Icon.png",
        "location": "On beach rocks",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "weather": "Any weather",
        "sell_nook": 200
    },
    {
        "name": "Yellow Butterfly",
        "image_url": "https://dodo.ac/np/images/4/43/Yellow_Butterfly_NH_Icon.png",
        "location": "Flying",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM \u00a07 PM",
        "weather": "Any except rain",
        "sell_nook": 160
    }
]