const fishArr =
[
    {
        "name": "Anchovy",
        "image_url": "https://dodo.ac/np/images/7/7f/Anchovy_%28Fish%29_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 AM  9 PM",
        "sell_nook": 200
    },
    {
        "name": "Angelfish",
        "image_url": "https://dodo.ac/np/images/c/cd/Angelfish_NH_Icon.png",
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 3000
    },
    {
        "name": "Arapaima",
        "image_url": "https://dodo.ac/np/images/b/b1/Arapaima_NH_Icon.png",
        "location": "River",
        "shadow_size": "Huge",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 10000
    },
    {
        "name": "Arowana",
        "image_url": "https://dodo.ac/np/images/6/67/Arowana_NH_Icon.png",
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 10000
    },
    {
        "name": "Barred Knifejaw",
        "image_url": "https://dodo.ac/np/images/d/d5/Barred_Knifejaw_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 5000
    },
    {
        "name": "Barreleye",
        "image_url": "https://dodo.ac/np/images/e/e0/Barreleye_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 PM  4 AM",
        "sell_nook": 15000
    },
    {
        "name": "Betta",
        "image_url": "https://dodo.ac/np/images/0/0b/Betta_NH_Icon.png",
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 2500
    },
    {
        "name": "Bitterling",
        "image_url": "https://dodo.ac/np/images/4/4d/Bitterling_NH_Icon.png",
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 900
    },
    {
        "name": "Black Bass",
        "image_url": "https://dodo.ac/np/images/0/00/Black_Bass_NH_Icon.png",
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 400
    },
    {
        "name": "Blowfish",
        "image_url": "https://dodo.ac/np/images/9/95/Blowfish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "9 PM  4 AM",
        "sell_nook": 5000
    },
    {
        "name": "Blue Marlin",
        "image_url": "https://dodo.ac/np/images/2/2a/Blue_Marlin_NH_Icon.png",
        "location": "Pier",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 10000
    },
    {
        "name": "Bluegill",
        "image_url": "https://dodo.ac/np/images/0/0c/Bluegill_NH_Icon.png",
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 180
    },
    {
        "name": "Butterfly Fish",
        "image_url": "https://dodo.ac/np/images/4/47/Butterfly_Fish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 1000
    },
    {
        "name": "Carp",
        "image_url": "https://dodo.ac/np/images/5/5d/Carp_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 300
    },
    {
        "name": "Catfish",
        "image_url": "https://dodo.ac/np/images/0/0d/Catfish_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM - 9 AM",
        "sell_nook": 800
    },
    {
        "name": "Char",
        "image_url": "https://dodo.ac/np/images/8/80/Char_NH_Icon.png",
        "location": "River (clifftop)",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 3800
    },
    {
        "name": "Cherry Salmon",
        "image_url": "https://dodo.ac/np/images/d/db/Cherry_Salmon_NH_Icon.png",
        "location": "River (clifftop)",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 1000
    },
    {
        "name": "Clown Fish",
        "image_url": "https://dodo.ac/np/images/4/4f/Clown_Fish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 650
    },
    {
        "name": "Coelacanth",
        "image_url": "https://dodo.ac/np/images/4/45/Coelacanth_NH_Icon.png",
        "location": "Sea (raining)",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 15000
    },
    {
        "name": "Crawfish",
        "image_url": "https://dodo.ac/np/images/9/96/Crawfish_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 200
    },
    {
        "name": "Crucian Carp",
        "image_url": "https://dodo.ac/np/images/f/f2/Crucian_Carp_NH_Icon.png",
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 160
    },
    {
        "name": "Dab",
        "image_url": "https://dodo.ac/np/images/1/1f/Dab_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 300
    },
    {
        "name": "Dace",
        "image_url": "https://dodo.ac/np/images/d/db/Dace_NH_Icon.png",
        "location": "River",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 240
    },
    {
        "name": "Dorado",
        "image_url": "https://dodo.ac/np/images/f/fe/Dorado_NH_Icon.png",
        "location": "River",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 AM  9 PM",
        "sell_nook": 15000
    },
    {
        "name": "Football Fish",
        "image_url": "https://dodo.ac/np/images/3/34/Football_Fish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM  9 AM",
        "sell_nook": 2500
    },
    {
        "name": "Freshwater Goby",
        "image_url": "https://dodo.ac/np/images/e/ec/Freshwater_Goby_NH_Icon.png",
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 400
    },
    {
        "name": "Frog",
        "image_url": "https://dodo.ac/np/images/2/2f/Frog_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 120
    },
    {
        "name": "Gar",
        "image_url": "https://dodo.ac/np/images/a/a2/Gar_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 6000
    },
    {
        "name": "Giant Snakehead",
        "image_url": "https://dodo.ac/np/images/5/50/Giant_Snakehead_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 5500
    },
    {
        "name": "Giant Trevally",
        "image_url": "https://dodo.ac/np/images/1/17/Giant_Trevally_NH_Icon.png",
        "location": "Pier",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 4500
    },
    {
        "name": "Golden Trout",
        "image_url": "https://dodo.ac/np/images/f/fc/Golden_Trout_NH_Icon.png",
        "location": "River (clifftop)",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "4 PM  9 AM",
        "sell_nook": 15000
    },
    {
        "name": "Goldfish",
        "image_url": "https://dodo.ac/np/images/7/71/Goldfish_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 1300
    },
    {
        "name": "Great White Shark",
        "image_url": "https://dodo.ac/np/images/2/20/Great_White_Shark_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 15000
    },
    {
        "name": "Guppy",
        "image_url": "https://dodo.ac/np/images/3/38/Guppy_NH_Icon.png",
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 1300
    },
    {
        "name": "Hammerhead Shark",
        "image_url": "https://dodo.ac/np/images/e/ec/Hammerhead_Shark_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 8000
    },
    {
        "name": "Horse Mackerel",
        "image_url": "https://dodo.ac/np/images/a/a3/Horse_Mackerel_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 150
    },
    {
        "name": "Killifish",
        "image_url": "https://dodo.ac/np/images/e/ea/Killifish_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 300
    },
    {
        "name": "King Salmon",
        "image_url": "https://dodo.ac/np/images/e/e1/King_Salmon_NH_Icon.png",
        "location": "River (mouth)",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 1800
    },
    {
        "name": "Koi",
        "image_url": "https://dodo.ac/np/images/2/2d/Koi_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 4000
    },
    {
        "name": "Loach",
        "image_url": "https://dodo.ac/np/images/a/a5/Loach_NH_Icon.png",
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 400
    },
    {
        "name": "Mahi-Mahi",
        "image_url": "https://dodo.ac/np/images/d/d6/Mahi-Mahi_NH_Icon.png",
        "location": "Pier",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 6000
    },
    {
        "name": "Mitten Crab",
        "image_url": "https://dodo.ac/np/images/9/9d/Mitten_Crab_NH_Icon.png",
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM  9 AM",
        "sell_nook": 2000
    },
    {
        "name": "Moray Eel",
        "image_url": "https://dodo.ac/np/images/3/3e/Moray_Eel_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Long",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 2000
    },
    {
        "name": "Napoleonfish",
        "image_url": "https://dodo.ac/np/images/3/30/Napoleonfish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Huge",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM  9 PM",
        "sell_nook": 10000
    },
    {
        "name": "Neon Tetra",
        "image_url": "https://dodo.ac/np/images/4/42/Neon_Tetra_NH_Icon.png",
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 500
    },
    {
        "name": "Nibble Fish",
        "image_url": "https://dodo.ac/np/images/0/0b/Nibble_Fish_NH_Icon.png",
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 1500
    },
    {
        "name": "Oarfish",
        "image_url": "https://dodo.ac/np/images/5/50/Oarfish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 9000
    },
    {
        "name": "Ocean Sunfish",
        "image_url": "https://dodo.ac/np/images/e/eb/Ocean_Sunfish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM  9 PM",
        "sell_nook": 4000
    },
    {
        "name": "Olive Flounder",
        "image_url": "https://dodo.ac/np/images/b/b3/Olive_Flounder_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Very large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 800
    },
    {
        "name": "Pale Chub",
        "image_url": "https://dodo.ac/np/images/e/e2/Pale_Chub_NH_Icon.png",
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 200
    },
    {
        "name": "Pike",
        "image_url": "https://dodo.ac/np/images/9/9f/Pike_NH_Icon.png",
        "location": "River",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 1800
    },
    {
        "name": "Piranha",
        "image_url": "https://dodo.ac/np/images/c/c6/Piranha_NH_Icon.png",
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "9 AM  4 PM &amp; 9 PM  4 AM",
        "sell_nook": 2500
    },
    {
        "name": "Pond Smelt",
        "image_url": "https://dodo.ac/np/images/0/0f/Pond_Smelt_NH_Icon.png",
        "location": "River",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 400
    },
    {
        "name": "Pop-Eyed Goldfish",
        "image_url": "https://dodo.ac/np/images/0/0d/Pop-Eyed_Goldfish_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 1300
    },
    {
        "name": "Puffer Fish",
        "image_url": "https://dodo.ac/np/images/e/ee/Puffer_Fish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 250
    },
    {
        "name": "Rainbowfish",
        "image_url": "https://dodo.ac/np/images/e/e7/Rainbowfish_NH_Icon.png",
        "location": "River",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 800
    },
    {
        "name": "Ranchu Goldfish",
        "image_url": "https://dodo.ac/np/images/3/35/Ranchu_Goldfish_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Small",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 AM  4 PM",
        "sell_nook": 4500
    },
    {
        "name": "Ray",
        "image_url": "https://dodo.ac/np/images/9/9b/Ray_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Very large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 AM  9 PM",
        "sell_nook": 3000
    },
    {
        "name": "Red Snapper",
        "image_url": "https://dodo.ac/np/images/c/c1/Red_Snapper_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 3000
    },
    {
        "name": "Ribbon Eel",
        "image_url": "https://dodo.ac/np/images/2/26/Ribbon_Eel_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Long",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 600
    },
    {
        "name": "Saddled Bichir",
        "image_url": "https://dodo.ac/np/images/4/46/Saddled_Bichir_NH_Icon.png",
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "9 PM  4 AM",
        "sell_nook": 4000
    },
    {
        "name": "Salmon",
        "image_url": "https://dodo.ac/np/images/c/ca/Salmon_NH_Icon.png",
        "location": "River (mouth)",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 700
    },
    {
        "name": "Saw Shark",
        "image_url": "https://dodo.ac/np/images/4/45/Saw_Shark_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "4 PM  9 AM",
        "sell_nook": 12000
    },
    {
        "name": "Sea Bass",
        "image_url": "https://dodo.ac/np/images/7/7f/Sea_Bass_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Very large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 400
    },
    {
        "name": "Sea Butterfly",
        "image_url": "https://dodo.ac/np/images/f/f7/Sea_Butterfly_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Tiny",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 1000
    },
    {
        "name": "Sea Horse",
        "image_url": "https://dodo.ac/np/images/d/dc/Sea_Horse_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 1100
    },
    {
        "name": "Snapping Turtle",
        "image_url": "https://dodo.ac/np/images/b/b1/Snapping_Turtle_NH_Icon.png",
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "9 PM  4 AM",
        "sell_nook": 5000
    },
    {
        "name": "Soft-Shelled Turtle",
        "image_url": "https://dodo.ac/np/images/e/eb/Soft-Shelled_Turtle_NH_Icon.png",
        "location": "River",
        "shadow_size": "Large",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 0,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM  9 AM",
        "sell_nook": 3750
    },
    {
        "name": "Squid",
        "image_url": "https://dodo.ac/np/images/b/bf/Squid_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 500
    },
    {
        "name": "Stringfish",
        "image_url": "https://dodo.ac/np/images/e/eb/Stringfish_NH_Icon.png",
        "location": "River (clifftop)",
        "shadow_size": "Very large",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "4 PM  9 AM",
        "sell_nook": 15000
    },
    {
        "name": "Sturgeon",
        "image_url": "https://dodo.ac/np/images/9/91/Sturgeon_NH_Icon.png",
        "location": "River (mouth)",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 10000
    },
    {
        "name": "Suckerfish",
        "image_url": "https://dodo.ac/np/images/d/de/Suckerfish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 1500
    },
    {
        "name": "Surgeonfish",
        "image_url": "https://dodo.ac/np/images/c/cb/Surgeonfish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Small",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 1000
    },
    {
        "name": "Sweetfish",
        "image_url": "https://dodo.ac/np/images/6/6a/Sweetfish_NH_Icon.png",
        "location": "River",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 900
    },
    {
        "name": "Tadpole",
        "image_url": "https://dodo.ac/np/images/b/bb/Tadpole_NH_Icon.png",
        "location": "Pond",
        "shadow_size": "Tiny",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 100
    },
    {
        "name": "Tilapia",
        "image_url": "https://dodo.ac/np/images/e/ef/Tilapia_NH_Icon.png",
        "location": "River",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 800
    },
    {
        "name": "Tuna",
        "image_url": "https://dodo.ac/np/images/4/4b/Tuna_NH_Icon.png",
        "location": "Pier",
        "shadow_size": "Huge",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 1,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 0,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 0,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 1,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 7000
    },
    {
        "name": "Whale Shark",
        "image_url": "https://dodo.ac/np/images/4/4f/Whale_Shark_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Very large (finned)",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 0,
        "n_m11": 0,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 0,
        "s_m5": 0,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 13000
    },
    {
        "name": "Yellow Perch",
        "image_url": "https://dodo.ac/np/images/6/67/Yellow_Perch_NH_Icon.png",
        "location": "River",
        "shadow_size": "Medium",
        "n_m1": 1,
        "n_m2": 1,
        "n_m3": 1,
        "n_m4": 0,
        "n_m5": 0,
        "n_m6": 0,
        "n_m7": 0,
        "n_m8": 0,
        "n_m9": 0,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 1,
        "s_m1": 0,
        "s_m2": 0,
        "s_m3": 0,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 1,
        "s_m7": 1,
        "s_m8": 1,
        "s_m9": 1,
        "s_m10": 0,
        "s_m11": 0,
        "s_m12": 0,
        "time": "All day",
        "sell_nook": 300
    },
    {
        "name": "Zebra Turkeyfish",
        "image_url": "https://dodo.ac/np/images/8/85/Zebra_Turkeyfish_NH_Icon.png",
        "location": "Sea",
        "shadow_size": "Medium",
        "n_m1": 0,
        "n_m2": 0,
        "n_m3": 0,
        "n_m4": 1,
        "n_m5": 1,
        "n_m6": 1,
        "n_m7": 1,
        "n_m8": 1,
        "n_m9": 1,
        "n_m10": 1,
        "n_m11": 1,
        "n_m12": 0,
        "s_m1": 1,
        "s_m2": 1,
        "s_m3": 1,
        "s_m4": 1,
        "s_m5": 1,
        "s_m6": 0,
        "s_m7": 0,
        "s_m8": 0,
        "s_m9": 0,
        "s_m10": 1,
        "s_m11": 1,
        "s_m12": 1,
        "time": "All day",
        "sell_nook": 500
    }
]